### ISSUE TITLE
Standardise Configuration files

### ISSUE THREAD

**Issue by apdibbo** [stfc/cloud#10]
Standardise to a particular format i.e. ini

This is so that metaconfig works nicely in Aquilon

**Comment by GooBall** [comment]
Currently we only have 3 configuration files and they are all `.config` files. Do we specifically need `.ini` files?

**Comment by apdibbo** [comment]
they dont specifically need to be .ini but ini format.

This is so that we can use Metaconfig to configure them nicely.

**Comment by GooBall** [comment]
The file will work with either a `=` or a`:` as a separator. So Metaconfig should play nicely with it all.
