### ISSUE TITLE
Can't delete VM

### ISSUE THREAD

**Issue by jodysalt** [stfc/cloud#104]
I can't delete machines "Bar" or "Bob".

My Fed Id id "elz24996".

This is what I got from the ajax request:

500 Internal Server Error

Internal server error [False, '[VirtualMachineAction] Error performing action "shutdown-hard" on virtual machine [33798]. This action is not available for state BOOT_FAILURE', 2048]

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/var/www/frontend/controllers/api/vm.py", line 96, in DELETE
    validateresponse(response)
  File "/var/www/frontend/helpers/oneerror.py", line 21, in validateresponse
    raise cherrypy.HTTPError(500, "Internal server error " + str(response))
HTTPError: (500, 'Internal server error [False, \'[VirtualMachineAction] Error performing action "shutdown-hard" on virtual machine [33798]. This action is not available for state BOOT_FAILURE\', 2048]')

**Comment by jodysalt** [comment]
Just noticed issue #99 is a duplicate - hopefully the extra info I've given you should allow you to fix it.

**Comment by jodysalt** [comment]
What is a little puzzling is that I can't find this 'BOOT_FAILURE' state referenced anywhere in Open Nebula's docs. I have extacted all the possible states (for ReAna) here:

https://github.com/DAaaS/reana/blob/8b01aabd10400fd84e9029eac60edcf06315f0cd/app/server/src/main/java/uk/ac/rl/reana/cloudclient/CloudClient.java#L122

The machine just gets listed as 'RUNNING'.

**Comment by jodysalt** [comment]
Ignore previous message I was looking at older documentation. So 'BOOT_FAILURE' does exist after all.

**Comment by jrha** [comment]
Should be fixed by #109.

**Comment by tofu-rocketry** [comment]
Was this fixed by #109?

**Comment by jrha** [comment]
I'm pretty sure it was, but it is probably irrelevant now anyway.
