### ISSUE TITLE
GUI ignores user choice of template when creating VMs

### ISSUE THREAD

**Issue by alahiff** [stfc/cloud#107]
When trying to create a new VM and I get to the "Select a template for Scientific Linux 7 No GUI" page, I see two choices: ScientificLinux-7-NoGui & WorldOfZFSv1. If I select ScientificLinux-7-NoGui it thinks I chose WorldOfZFSv1. Because of this I can't use the STFC GUI for creating VMs.

**Comment by apdibbo** [comment]
This is a display issue and does not effect what is being passed in to OpenNebula as the template id is still correct

**Comment by apdibbo** [comment]
fixed in #108
