### ISSUE TITLE
Newly created VMs appear older than they are

### ISSUE THREAD

**Issue by jrha** [stfc/cloud#117]
Newly created VMs currently show up as being created "an hour ago", this is presumably due to the creation time in UTC being compared to the system time in BST.

**Comment by JHaydock-Pro** [comment]
I believe I have resolved this, you were correct it was a UTC vs system time issue.

**Comment by tofu-rocketry** [comment]
Please edit the description of #114 and add a [keyword](https://help.github.com/articles/closing-issues-using-keywords/) so that this issue will close when that PR is merged.
