### ISSUE TITLE
Add a VM view

### ISSUE THREAD

**Issue by apdibbo** [stfc/cloud#12]
Add a view for vm detail and additional functionality

**Comment by GooBall** [comment]
Can this be elaborated upon?

**Comment by GooBall** [comment]
So just to beef this out a bit, the current plans for this are:
- The view for each VM will be accessible via a button next to the 'GUI' and 'Delete' buttons.
- The view will contain more detailed information and options for the VM in question including things like a helpdesk ticket button (#6), rev counters for cpu and memory (#13), the ability to add attach/detach storage (#15), who created the VM (#56), and so on.

**Comment by jrha** [comment]
Likely that this won't be implemented, this is the "simple" web portal.
