### ISSUE TITLE
Aquilon integration

### ISSUE THREAD

**Issue by apdibbo** [stfc/cloud#16]
Add ability to select a sandbox and personality when creating a VM

**Comment by apdibbo** [comment]
We will do this in two stages, the first being adding free text fields to select archetype, sandbox and personality. 
For the second stage we will add drop downs to select each of the above (archetype, sandbox users, sandbox and personality) which will be populated with data from Aquilon

**Comment by GooBall** [comment]
The first stage of this was implemented by #38 so the basic functionality is there. 
I'll leave this open but move it to a mid term milestone.
