### ISSUE TITLE
Typo wskey in server.py

### ISSUE THREAD

**Issue by alvarosimon** [stfc/cloud#17]
I get this error from server.py using VNC keys

 # python server.py
 Traceback (most recent call last):
 File "server.py", line 47, in <module>
 wsparams.append('--key=' + cherrypy.config.get("key"))
 TypeError: cannot concatenate 'str' and 'NoneType' objects

because a type in:
https://github.com/stfc/cloud/blob/master/server.py#L47

it should be
 wsparams.append('--key=' + cherrypy.config.get("wskey"))

**Comment by GooBall** [comment]
Fixed in #18
