### ISSUE TITLE
Restructuring of menus

### ISSUE THREAD

**Issue by GooBall** [stfc/cloud#19]
As things stand, there are two menus; The main one and the side one. 

Currently the main menu has only one link ('Machines') that links to the overview page of your running VMs and the side menu has everything else.

I would argue that the main menu should have something along the lines of:
- `Home` - I know the logo links but not everyone clicks logos.
- `What we offer` There is already a bit of this around on the 'Infrastructure' and 'Welcome' slides, but a page that goes into more detail would be good.
- `Terms of Service` sort of as per #1 but it might as well be global.
- `FAQs` Currently, you have to login to see them - might as well make them visible from the start.
- `My Machines` Essentially the current 'Machines' tab - but does it need to be visible to people who are not logged in?

Any thoughts?

**Comment by GRyall** [comment]
Machines tab should defintily only be visible to people logged in. Not sure about a what we offer tab though.  I agree broadly with the rest.

**Comment by GooBall** [comment]
Resolved in #43
