### ISSUE TITLE
Differentiate between 'Booting up' and 'Active'

### ISSUE THREAD

**Issue by MarcusNoble** [stfc/cloud#21]
The machine list shows any provisioned machine as 'Active' regardless of its ready state. If trying to ssh (rather than using the gui) while the machine is still booting up you get a very unhelpful message. It'd be nice to be able to show the machine as still booting and when ready to accept connections then show it as 'Active' (or perhaps 'Ready').

**Comment by jrha** [comment]
:+1:

If I query my list of VMs using the CLI I get intermediate states such as `prolog`, instead of exposing this extra information, how about a little progress bar or similar?
A contextualisation hook could also be used to track when the OS has finished booting.

It would be useful to track the timings of these events as metrics on how the cloud infrastructure is performing.

**Comment by apdibbo** [comment]
Add a progress bar (5 steps - Pending, Prolog, Boot, "Running" [machine is Running but has not finished the OS boot] and Ready) for Instantiating

Add a page that the VM can post to when it has finished booting to notify the Cloud

**Comment by jrha** [comment]
If we use the word "boot" in a user facing context it should probably refer to OS boot to avoid confusion.

How about (and maybe then only as hover over text?):
1. Pending
   - 0% / grey
2. Transferring
   - 25% / red
3. Building
   - 50% / orange
4. Booting
   - 75% / yellow
5. Ready
   - 100% / green

**Comment by apdibbo** [comment]
I agree

**Comment by apdibbo** [comment]
Initially add a progress bar to show 1-4 in @jrha's list above (replace Booting with Active).

We will add a page that the VM can post to when it has finished booting for the fifth state later

**Comment by GooBall** [comment]
This was implemented with #39.

I'll create a new issue for putting in place the final part of this (getting a VM to post to a page when it has finished booting) as it has no connection to this system.
