### ISSUE TITLE
VM history page shows that running VMs can time travel back to the 1970s

### ISSUE THREAD

**Issue by GooBall** [stfc/cloud#22]
![screenshot from 2015-09-22 11 56 21](https://cloud.githubusercontent.com/assets/5050301/10016729/0c83578c-6121-11e5-94a2-184ecb557a8a.png)
The 'end' section should probably have a '----' in place of the timestamp for a running VM.

**Comment by MarcusNoble** [comment]
Looks fine on mine...
![image](https://cloud.githubusercontent.com/assets/4919969/10017867/d7d4b838-6129-11e5-9b6e-dcc76a6e6861.png)

**Comment by GooBall** [comment]
Huh well that's odd. I'll dig into it a bit then...

**Comment by GooBall** [comment]
It looks like I messed something up - I reverted the files I was working on and it's now displaying as it should. :tada:
