### ISSUE TITLE
Clickthrough menu requires click on final option even when there is only one option

### ISSUE THREAD

**Issue by GRyall** [stfc/cloud#28]
I like the new click-through menu to choose a template for a new VM. However when I reach the final 'option' I have to click the button even if there is only one option for me to choose, it would be great if it was selected for me automatically.

**Comment by GRyall** [comment]
Actually given the structure, it would be good if at every level, if there is only one option it is selected for me.

**Comment by apdibbo** [comment]
fixed by #31
