### ISSUE TITLE
Ugly grey bar doesn't appear on FAQ page

### ISSUE THREAD

**Issue by GRyall** [stfc/cloud#88]
Not saying that this is an issue really - why do we have it on any of the pages? All it has is a copyright statement and on a wide-screen monitor it takes a load of screen space.

**Comment by GooBall** [comment]
The footer is there for a handful of reasons:
*It balances the page visually (with such a strong coloured header like we have things can look odd on pages that don't fill the height of the screen). It also lets users know that they are at the bottom of the page.
*It is universal practice to include a copyright statement on every page of a website - the footer is the standard place to do this.
*Having a footer also enables you to add links and other information at a later date (things like ToS and FAQs).

I am unable to replicate your missing footer - it shows on all pages. If you can recreate it, please take a screenshot and copy me the page source.
