### ISSUE TITLE
Drop down lists for aquilon managed VMs don't work

### ISSUE THREAD

**Issue by jrha** [stfc/cloud#90]
With my desktop colour scheme they are also unreadable (don't set foreground colours without setting background colours please).

**Comment by GooBall** [comment]
The dropdown menus not being populated is an issue with server - It will be fixed.

As for your menus being unreadable, it sounds like it is an oversight of your theme not the design of the frontend. I'll see what I can do about a workaround - but not promising anything.

**Comment by jrha** [comment]
Give then the class "form-control"
