### ISSUE TITLE
Ubuntu is Scientific Linux, apparently

### ISSUE THREAD

**Issue by tofu-rocketry** [stfc/cloud#95]
Dev build. Ubuntu-12-NoGui listed under SL.

New Machine > SL > 6 > No GUI > Ubuntu!

Haven't spotted any others listed under the wrong section...yet.

**Comment by GooBall** [comment]
I'm happy to say this is only the case on the dev setup (due to how things are configured) and won't be an issue on the production instance. Good spot though.
