### ISSUE TITLE
VM incorrectly shown to be running and can't be deleted

### ISSUE THREAD

**Issue by alahiff** [stfc/cloud#99]
I have a VM (vm50) which is in the Running state according to the UI but is actually dead or broken in some way. If I try and delete it I get a message:

> The cloud may be experiencing problems. Please try again later.

The problem occurs on both the production UI and the dev UI.

**Comment by alahiff** [comment]
I just tried deleting 3 running VMs and each time was given the same error message. 2 were successfully deleted but one is immortal.

**Comment by jrha** [comment]
Should be fixed by #109.

**Comment by tofu-rocketry** [comment]
Was this fixed by #109?
